### ISSUE TITLE
kanils' dependency fails to compile on rustc 1.36.0

### ISSUE THREAD

**Issue by koba-e964** [frugalos/kanils#13]
In `rustc 1.36.0`, `cargo build --release` fails with the following error message:
```
$ cargo build --release
   Compiling trackable v0.2.22
   Compiling structopt v0.2.18
   Compiling rustyline v2.1.0
   Compiling indicatif v0.11.0
error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
   --> /home/koba-e964/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-2.1.0/src/lib.rs:639:43
    |
639 |             editor.add_history_entry(line.as_ref());
    |                                           ^^^^^^

   Compiling prometrics v0.1.11
error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: Could not compile `rustyline`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Probably we need to upgrade `rustyline` from 2.1.0 to 5.0.0? https://docs.rs/rustyline/5.0.0/rustyline/
Related issue: https://github.com/rust-lang/rust/issues/60958
